Objetivo 4
Xileon310/GoParty pull request #33
Opened 2021-12-10 19:46 UTC by Xileon310

- Añade ruta para tests. Avanza #27
- Añade comprobaciones para tests. Avanza #27
- Añade test para localidad. Closes #28
- Se añade test para provincia. Closes #29
- Se añade test para país. Closes #30
- Se añade test para título. Closes #31
- Se añade test para categoría. Closes #32

2021-12-10 20:25 UTC, Xileon310 commented
@JJ Estaría listo para revisión

2021-12-15 23:17 UTC, Xileon310 commented
@alexespana @lentes4k @JAntonioVR

2021-12-16 08:19 UTC, lentes4k commented
Para empezar, muy buen curro. A simple vista lo veo bastante bien. Te ha faltado pegar en el cuerpo del PR el código que JJ pide en las nuevas entregas. Te lo dejo aquí: 
`* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?`
Tampoco soy un experto en GO pero si ya atrapas los errores en las clases correspondientes de cada objeto, ¿por qué vuelves a poner un mensaje en el código con el que testeas?
Bastaría con recoger el mensaje que ya te atrapa tu manejador de errores, ¿no?

2021-12-16 08:25 UTC, lentes4k commented on pkg/actividad/actividad.go
> +
Tanto aquí como en zona.go podrías llevar los errores a un archivo a parte para usar mejores prácticas

2021-12-16 08:30 UTC, Mapachana requested changes

2021-12-16 08:30 UTC, Mapachana commented on docs/tests.md
> +Para la realización de los tests unitarios que se piden en el objetivo se ha creado un fichero denominado actividad_test.go en el que se declaran los tests correspondientes a la entidad Actividad y a
En la documentación has dicho que has elegido la biblioteca testing, pero no has justificado la elección de esta. ¿Por qué has usado testing y no otra? ¿Qué requisitos tiene tu proyecto para haberla elegido?

2021-12-16 08:32 UTC, Mapachana requested changes

2021-12-16 08:32 UTC, Mapachana commented on docs/tests.md
> +Por otro lado se ha seguido el convenio de valor-error propio de go en las clases Actividad y Zona. Las funciones de creación de un objeto realizarán diversas comprobaciones, en el caso de haber un e
¿Devolver nil está bien? ¿No se podría comprobar si se alza un error en lugar del valor devuelto?

2021-12-16 08:32 UTC, JAntonioVR requested changes
En general está muy bien, salvo la documentación que habría que detallarla un poco más y te he hecho también algunas sugerencias en los tests. Si no estás de acuerdo con algo dímelo, y si he dicho algo incorrecto debido a que no controlo el lenguaje dímelo sin miedo.

2021-12-16 08:32 UTC, JAntonioVR commented on docs/tests.md
> +Para la realización de los tests unitarios que se piden en el objetivo se ha creado un fichero denominado actividad_test.go en el que se declaran los tests correspondientes a la entidad Actividad y a
Deberías justificar por qué utilizas la biblioteca testing. Está muy bien utilizada siguiendo estándares y tal pero ¿por qué esa biblioteca y no otra?

2021-12-16 08:32 UTC, JAntonioVR commented on pkg/actividad/actividad_test.go
> +// ---------------------- Tests del Objeto Valor Zona ----------------------
Me gusta la forma en la que gestionas los posibles errores dentro de las propias clases y también dentro de los tests, pero quizá deberías añadir test que comprueben el correcto funcionamiento, no sólo la buena gestión de errores. Por ejemplo, yo hice test que creaban objetos y se aseguraban (con assert) de que en efecto los campos importantes no estaban vacíos y el objeto estaba bien creado. Aún así me gustan tus test gestionando los errores, solo es una sugerencia para añadir otros tests.

2021-12-16 08:32 UTC, JAntonioVR commented on pkg/actividad/actividad.go
> +	}
Muy buena gestión de errores, pero yo tendría en cuenta la posibilidad de que la zona que llega en el constructor sea `nil`. Aunque por otra parte si termina de construirse es porque no peta el constructor de Zona (yo es que soy muy de dobles comprobaciones, pero es sólo una sugerencia).

2021-12-16 09:19 UTC, alexespana requested changes
En general, está bastante correcto, aunque te falla la **justificación técnica** de la bilioteca de test elegida, revisa los comentarios que te he dejado por aquí abajo.

2021-12-16 09:19 UTC, alexespana commented on docs/tests.md
> +Para la realización de los tests unitarios que se piden en el objetivo se ha creado un fichero denominado actividad_test.go en el que se declaran los tests correspondientes a la entidad Actividad y a
Como dicen mis compañeros, deberías de justificar por qué utilizas la biblioteca testing en algún lugar de la documentación. En cualquier justificación técnica siempre es necesario que establezcas unos **requisitos** antes de nada, realices una **búsqueda parametrizada** de los mismos y finalmente elijas aquel que mejor los cumpla.

2021-12-16 09:19 UTC, alexespana commented on docs/tests.md
> +Por otro lado se ha seguido el convenio de valor-error propio de go en las clases Actividad y Zona. Las funciones de creación de un objeto realizarán diversas comprobaciones, en el caso de haber un e
Revisando la documentación de Go, veo que has seguido las mejores prácticas para la realización de tests, por esta parte :100: .

2021-12-16 11:30 UTC, Xileon310 commented on docs/tests.md
> +Para la realización de los tests unitarios que se piden en el objetivo se ha creado un fichero denominado actividad_test.go en el que se declaran los tests correspondientes a la entidad Actividad y a
Listo, documentado [aquí](docs/tests.md)

2021-12-16 11:31 UTC, Xileon310 commented on docs/tests.md
> +Para la realización de los tests unitarios que se piden en el objetivo se ha creado un fichero denominado actividad_test.go en el que se declaran los tests correspondientes a la entidad Actividad y a
Listo, documentado en el fichero corresopndiente.

2021-12-16 11:34 UTC, Xileon310 commented on pkg/actividad/actividad_test.go
> +// ---------------------- Tests del Objeto Valor Zona ----------------------
Entiendo tu punto de vista, y ciertamente lo comparto, pero es cierto que siguiendo el principio F.I.R.S.T. y haciendo los tests lo más sencillos y rápidos posibles, el uso de la función assert añadiría carga extra en algo que podemos considerar obvio, pues lo hace el compilador. Si introducimos un número como título de una actividad (que debe ser string), el propio compilador no dará error para ello.

Es cierto que podría diseñar un test con la función assert que compruebe que efectivamente la zona que se ha proporcionado para la creación del objeto actividad es correcta.

2021-12-16 11:38 UTC, Xileon310 commented on pkg/actividad/actividad.go
> +	}
Es cierto que se podría hacer, pero sería añadir código innecesario (además de que no es posible hacer lo que pides en este lenguaje de programación).

Surgen los siguientes problemas:
- nil es un valor indeterminado que se usa solo para punteros, interfaces, mapas, slices, canales y funciones. En este caso se usa en la interfaz ``error```, pero no podría hacer lo mismo para el objeto de tipo Zona (salvo que lo enviase a la función como un puntero, cosa que no debería por el siguiente motivo).
- El mero hecho de que el puntero sea indeterminado no aporta nada a la creación del objeto, puesto que si ha pasado por el constructor de Zona y ha sido validado (ha pasado los tests) es que se debe haber creado correctamente. Es lo que comentabas anteriormente de la doble comprobación.

2021-12-16 11:38 UTC, Xileon310 commented on docs/tests.md
> +Para la realización de los tests unitarios que se piden en el objetivo se ha creado un fichero denominado actividad_test.go en el que se declaran los tests correspondientes a la entidad Actividad y a
Listo, justificado en el archivo correspondiente.

2021-12-16 11:59 UTC, Xileon310 commented on docs/tests.md
> +Por otro lado se ha seguido el convenio de valor-error propio de go en las clases Actividad y Zona. Las funciones de creación de un objeto realizarán diversas comprobaciones, en el caso de haber un e
Realmente se devuelven dos valores, pero se comprueba el segundo en el caso de errores (se deshecha el primero haciendo uso de la variable _).

Respecto a nil, es el convenio de go para tratar los errores. Somos nosotros los que debemos asegurarnos de que si pasa "lo que no quieres que pase" se devuelva ese valor, que no es más que un valor indeterminado para punteros, funciones interfaces, mapas y slices.

Entiendo que te refieres a capturar los errores como se haría por ejemplo en Java, con un bloque try/catch, pero lametablemente eso no existe en Golang. Este lenguaje se caracteriza por tener errores estrictos que terminan el programa o funciones que permiten evitar el tratamiento de errores.

Te pongo un ejemplo:

Los desarrolladores de golang se suelen quejar de que las personas suelen hacer sentencias try/catch realmente extensas, que no siguen buenas prácticas de código limpio y sencillo. Por lo que esta función (que da error en tiempo de compilación si el fichero no existe)
```shell
f := os.Open("filename.txt")
```

Se trataría de la siguiente forma:
```shell
f, _ := os.Open("filename.txt")
```

Otro ejemplo que motiva este paradigma: 

Imagina que en Java abres un fichero y empiezas a escribir en él, y llegado a un punto debes cerrar el fichero (debes cerrar el stream), por lo que deberías buscar en un posible try/catch extenso las opciones que deberías limpiar antes de cerrar.
En golang por ejemplo se usa la función defer(), que abre un fichero y simplemente lo cierra cuando ejecutas una función que deseas, por lo que te permite olvidar de los errores comunes por no cerrar un fichero, de que el fichero no exista, de que se te haya olvidado limpiar alguna opción, etc.

2021-12-16 12:01 UTC, Xileon310 commented on pkg/actividad/actividad.go
> +
Es cierto, pero por sencillez y mayor interacción con la terminal en la ejecución de los tests, opté por hacer un simple print en el shell. En un futuro seguramente lo cambie a un archivo.

2021-12-16 12:11 UTC, JAntonioVR commented on pkg/actividad/actividad_test.go
> +// ---------------------- Tests del Objeto Valor Zona ----------------------
Sigo pensando que deberías comprobar el buen funcionamiento de alguna forma, pero entiendo tu punto de vista de querer hacer rápidos los tests.

2021-12-16 12:15 UTC, JAntonioVR commented on pkg/actividad/actividad.go
> +	}
Cuestiones del lenguaje entonces, si es inviable o dificulta el desarrollo de los test solo queda confiar en el objeto de tipo Zona y en que no vaya a tomar valores incorrectos (y para eso están sus propios tests)

2021-12-16 12:21 UTC, JAntonioVR requested changes
Ya casi por mi parte, una pequeña cuestión de estructura en la documentación y lo tienes

2021-12-16 12:23 UTC, Xileon310 commented
> Ya casi por mi parte, una pequeña cuestión de estructura en la documentación y lo tienes

¿A qué te refieres con la estructura de la documentación?

2021-12-16 12:24 UTC, JAntonioVR requested changes
Te dejo aquí la review que antes se me pasó

2021-12-16 12:24 UTC, JAntonioVR commented on docs/tests.md
> +Realmente la diferencia radicaba entre usar Testify y testing para este proyecto, y nos decantamos por testing por seguir los estándares marcados para go (que no quiere decir que sea lo óptimo) y por
Muy buena justificación, pero deberías hacer la comparación de alternativas antes de comunicar la decisión final

2021-12-16 12:25 UTC, JAntonioVR commented
> > Ya casi por mi parte, una pequeña cuestión de estructura en la documentación y lo tienes
> 
> ¿A qué te refieres con la estructura de la documentación?

Te lo acabo de poner, fallo mío antes

2021-12-16 12:26 UTC, Xileon310 commented on docs/tests.md
> +Realmente la diferencia radicaba entre usar Testify y testing para este proyecto, y nos decantamos por testing por seguir los estándares marcados para go (que no quiere decir que sea lo óptimo) y por
Listo, es verdad, es mejor cambiar la estructura para que quede antes la comparativa que la decisión final

2021-12-16 12:29 UTC, Mapachana commented on docs/tests.md
> +Por otro lado se ha seguido el convenio de valor-error propio de go en las clases Actividad y Zona. Las funciones de creación de un objeto realizarán diversas comprobaciones, en el caso de haber un e
No lo sabía, me parece supercurioso. Lo has explicado muy bien, me ha quedado clarísimo. Muchísimas gracias!

2021-12-16 12:29 UTC, JAntonioVR approved these changes
Palantísimo :+1: :tada:

2021-12-16 12:30 UTC, Xileon310 commented on docs/tests.md
> +Por otro lado se ha seguido el convenio de valor-error propio de go en las clases Actividad y Zona. Las funciones de creación de un objeto realizarán diversas comprobaciones, en el caso de haber un e
Muchas gracias a ti también!!

PD: Tu avatar mola mucho

2021-12-16 12:33 UTC, Mapachana commented
Yo lo veo bastante bien ya :smile:

2021-12-16 12:33 UTC, Mapachana approved these changes

2021-12-16 12:55 UTC, Xileon310 commented on pkg/actividad/actividad.go
> +
> Tampoco soy un experto en GO pero si ya atrapas los errores en las clases correspondientes de cada objeto, ¿por qué vuelves a poner un mensaje en el código con el que testeas?

No es ser experto en GO, es un concepto básico que había entendido mal sobre los tests del objetivo. Ahora los he corregido para que sean los correctos (aunque aparezcan menos) pero con más sentido.

2021-12-16 12:56 UTC, Xileon310 commented
En primer lugar gracias a todos, ha sido una gran ayuda y he cambiado bastantes cosas que no estaban bien (documentación y tests sobre todo).

@lentes4k @alexespana Si lo veis bien vosotros también aprobad los cambios y avisaré al profesor esta tarde para la corrección.

2021-12-16 13:21 UTC, lentes4k commented on pkg/actividad/actividad.go
> +
genial entonces!

2021-12-16 13:21 UTC, lentes4k approved these changes
Buen curro y muy buenas explicaciones aquí en el PR 😄

2021-12-16 15:08 UTC, Xileon310 commented
@JJ Estaría listo para revisión.

2021-12-16 16:47 UTC, JJ requested changes
La verdad es que habéis hecho un currazo encomiable, pero falta algo fundamental: hay que tener completa, y testear, la lógica de negocio o parte de ella.

2021-12-16 19:17 UTC, Xileon310 commented
> La verdad es que habéis hecho un currazo encomiable, pero falta algo fundamental: hay que tener completa, y testear, la lógica de negocio o parte de ella.

Es totalmente cierto, cuando he leído el mensaje se me ha venido a la cabeza. Hace tiempo cerré la primera Historia de Usuario creyendo haberla finalizado, pero no ha sido hasta ahora que nos podemos asegurar que dicha historia puede darse por completada. Gracias a los tests nos aseguramos la correcta definición y creación de una actividad, que es la entidad principal con la que se relaciona la lógica de negocio.

Todo ello ha sido explicado en el fichero tests.md y más desarrollado, además de que se ha hecho mención en el cuerpo del PR. Por otro lado se ha movido la Historia de Usuario correspondiente al hito en el que se está trabajando, que es a donde se corresponde. Como ya ha explicado en otras ocasiones, las Historias de Usuario se mueven a lo largo de los hitos.

Respecto a la experiencia de trabajo grupal, ha sido bastante gratificante y muy entretenido, pero sobre todo es por el rápido feedback que se ha tenido por parte de mis compañeros.

@JJ Ahora estaría listo para revisión.

2021-12-16 19:48 UTC, JJ requested changes
Realmente es el mismo comentario que antes: debes crear el código de la lógica de negocio, o parte, y testearla. También asegúrate que este código está en un PMV y que este describe correctamente lo que va a resultar de esto.

2021-12-16 19:48 UTC, JJ commented on README.md
> +Esta aplicación dispondría de un sistema en el que cualquier usuario podría crear una actividad con ciertas características y otros usuarios pudiesen apuntarse a ella, consiguiendo por tanto, que dif
Me temo que es el *código* de la lógica de negocio lo que tienes que desarrollar. Tampoco un chat es realmente lógica de negocio. Repasa el concepto, por favor.

2021-12-16 19:48 UTC, JJ commented on pkg/actividad/actividad_test.go
> +// ---------------------- Tests del Objeto Valor Zona ----------------------
Hazle caso a @JAntonioVR . Realmente sólo estás testeando que se crean correctamente, no hay ninguna funcionalidad que estés testeando.

2021-12-16 21:06 UTC, Xileon310 commented on README.md
> +Esta aplicación dispondría de un sistema en el que cualquier usuario podría crear una actividad con ciertas características y otros usuarios pudiesen apuntarse a ella, consiguiendo por tanto, que dif
El chat era un vestigio de un anterior objetivo que se me pasó quitar, lo comentamos en clase un día y decidí quitarlo.

2021-12-16 21:09 UTC, Xileon310 commented
> Hazle caso a @JAntonioVR . Realmente sólo estás testeando que se crean correctamente, no hay ninguna funcionalidad que estés testeando.

Creo que lo estaba entendiendo mal, simplemente estaba testeando (en la creación de Zona y Actividad) que el objeto no admitía que un argumento fuese válido, pero en ningún momento testeaba si ese objeto realmente se había creado con la información que yo quería. Se ha resuelto este problema.

Por otro lado, me ha parecido pobre simplemente la comprobación de dos constructores que por sí solos no pueden desarrollar la lógica de negocio (esto es lo que estaba entendiendo mal). Para resolver esto, he añadido también varias funcionalidades y nuevas issues #37 #38 junto con un nuevo test.

@JJ Perdón por la molestia, espero que ya esté listo para pasar el objetivo.

2021-12-17 06:45 UTC, JJ approved these changes
:+1: bien currado por parte de todo el mundo.
No tienes por qué poner en el milestone que "incluya tests". Va implícito que hay que testearlo con los criterios de viabilidad que incluyas.

2021-12-17 07:24 UTC, merged