Objetivo 5
Xileon310/GoParty pull request #36
Opened 2021-12-16 09:17 UTC by Xileon310

- Cambia nombre de repositorio
- Añade Dockerfile. Avanza #34

2021-12-16 11:07 UTC, Xileon310 commented
@danifm1321 @paula1999 @JAntonioVR

2021-12-16 13:16 UTC, JAntonioVR requested changes
Muy muy buen trabajo Jose. Una pequeña recomendación de cara al objetivo 6 y por mí lo tienes. 

PD: Muy buen trabajo en la documentación

2021-12-16 13:16 UTC, JAntonioVR commented on Dockerfile
> +FROM golang:alpine
Deberías especificar qué versión usa este contenedor base o quizá especificarle una en base a tus necesidades. Lo digo porque de cara al objetivo 6 tendrás que parametrizar la construcción del contenedor para testear la aplicación en distintas versiones del lenguaje. He visto que hay en dockerhub imágenes oficiales desde la 1.16 a la 1.18.

2021-12-16 13:16 UTC, JAntonioVR commented on docs/dockerfile.md
> +Podría usarse cualquier imagen para la creación, puesto que se puede arrancar cualquier versión, hacer una instalación limpia del lenguaje golang y las dependencias necesarias y bastaría, pero en est
Has optado por usar imágenes oficiales, pero especifica de qué son esas imágenes oficiales.

2021-12-17 06:40 UTC, JJ reviewed
Además, el milestone al que está asignado es demasiado genérico y no incluye lo que está en este PR.

2021-12-17 07:46 UTC, Xileon310 commented on docs/dockerfile.md
> +Podría usarse cualquier imagen para la creación, puesto que se puede arrancar cualquier versión, hacer una instalación limpia del lenguaje golang y las dependencias necesarias y bastaría, pero en est
Listo, se ha especificado que se usarán imágenes oficiales de golang

2021-12-17 07:47 UTC, Xileon310 commented on Dockerfile
> +FROM golang:alpine
Listo, se ha especificado la versión 1.17, aunque sería indiferente usar la 1.16 y la 1.18.

2021-12-17 07:49 UTC, Xileon310 commented
> Además, el milestone al que está asignado es demasiado genérico y no incluye lo que está en este PR.

Arreglado, y definitivamente cerraré el PR tras la revisión para crear una nueva rama con muchos menos commits y más claros.

2021-12-17 09:12 UTC, Xileon310 commented
@JJ Listo para revisión.

2021-12-22 11:41 UTC, Xileon310 commented
Puesto que no ha habido comunicación adicional, cierro el PR para realizar los cambios de forma más estructurada.

2021-12-22 11:41 UTC, closed without merging

2021-12-22 16:14 UTC, JJ commented
Perdón, se me había pasado. Voy a revisar el nuevo.