Update Objetivo 6
Xileon310/GoParty pull request #43
Opened 2022-01-04 22:27 UTC by Xileon310

- Añade documentación de CI. Closes #40
- Añade clave CI. Avanza #41
- Añade configuración para CircleCI. Closes #41
- Añade tests en Github Actions. Closes #42
- Actualiza información matrix. #40

2022-01-04 23:28 UTC, Xileon310 commented
## Duda para revisores

Tengo una duda, no sé si estoy en el camino correcto puesto que uno de mis tests es comprobar que la imagen se "buildea" y se "pushea" correctamente a DockerHub. Puesto que los otros tests se basan en esta imagen, esto puede dar una condición de carrera (o eso creo) puesto que se supone que todos los tests se ejecutan concurrentemente.

¿Debería cambiar los tests dependientes con una orden tal que así?
```shell
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed
```

2022-01-07 06:28 UTC, JJ commented
⛹ Revisores → @Asmilex @Antobio17 @joaquingv12

2022-01-07 18:33 UTC, Asmilex approved these changes
En principio, lo veo todo bien. No he sido capaz de encontrar nada digno de mención 🐳

2022-01-07 18:33 UTC, Asmilex commented on docs/CI.md
> +- **Buildbot**: Algo menos conocido que los anteriores pero también muy útil, es un framework de Integración Continua que automatiza la compilación y realización de tests en los proyectos. Es un proy
Bien documentado 👍🏼.

2022-01-07 18:41 UTC, Asmilex commented
> ## Duda para revisores
> Tengo una duda, no sé si estoy en el camino correcto puesto que uno de mis tests es comprobar que la imagen se "buildea" y se "pushea" correctamente a DockerHub. 

(¿con tests te refieres a workflows, no?)

> Puesto que los otros tests se basan en esta imagen, esto puede dar una condición de carrera (o eso creo) puesto que se supone que todos los tests se ejecutan concurrentemente.
> 
> ¿Debería cambiar los tests dependientes con una orden tal que así?
> 
> ```shell
> # Only trigger, when the build workflow succeeded
> on:
>   workflow_run:
>     workflows: ["Test-Que-Buildea-Imagen-Y-Pushea"]
>     types:
>       - completed
> ```

Con respecto a esto... Es un tema algo más complicado. Hay un detalle que hay que analizar primero.

En principio, tu imagen se debería reconstruir cada vez que se actualicen las dependencias en una rama específica. En tu caso, `master`, como veo en el archivo [dockerhub.yml](https://github.com/Xileon310/GoParty/blob/Objetivo-6/.github/workflows/dockerhub.yml). Eso significa que, si añades una dependencia en alguna rama de objetivo, el contenedor no se actualizará. Así que no podrá pasar los tests. 

Ahora bien, una vez se encuentre una forma de sortear este problema, no debería haber ninguna condición de carrera si se un procedimiento fijo. O, al menos, según entiendo yo el problema que comentas. 

Primero, deberías committear y pushear el cambio de dependencia, para que así el contenedor se actualice. Una vez esté subido a dockerhub, cualquier programa puede solicitar **una copia de ese contenedor**, de forma que se realicen los tests necesarios. 

Así que, en ese punto, te da igual que haya concurrencia entre CIs. Mientras el contenedor de Dockerhub esté al día con todas las dependencias, que los sistemas ejecuten en paralelo lo que quieran. Más tiempo nos ahorramos. No se van a fastidiar los unos a los otros. 

¿He entendido mal el problema, o te referías a esto?

2022-01-08 20:30 UTC, Xileon310 commented
En primer lugar perdón por la tardanza, por temas de covid no he podido trabajar todo lo que me hubiese gustado en el proyecto.

> (¿con tests te refieres a workflows, no?)

Sí, perdón, que no me he explicado con la suficiente propiedad.

> Primero, deberías committear y pushear el cambio de dependencia, para que así el contenedor se actualice. Una vez esté subido a dockerhub, cualquier programa puede solicitar una copia de ese contenedor, de forma que se realicen los tests necesarios.

Esto es lo que no tenía tan claro, en mi caso estaba imaginándome la situación en la que se pushean todos los cambios de una vez, incluyendo dependencias, lo que creo que provocaría condición de carrera entre workflows por ejecutarse en paralelo (puesto que se ejecutaría a la vez el deploy de la imagen de Docker con los tests).

Y por último muchas gracias por tu ayuda. ¡Me ha servido de mucho!

2022-01-08 20:35 UTC, Xileon310 commented
@JJ Estaría listo para revisión.

2022-01-09 13:49 UTC, Xileon310 commented
Perdón, he modificado la Github Action eliminando la directiva de branches.

Ahora sí estaría listo para revisión.

2022-01-09 16:19 UTC, JJ requested changes
Lo siento, no has justificado ni las versiones usadas de Go (que además, testeas dos veces) ni los sistemas que usas, por lo que no has cumplido el objetivo, que era entender entre otras cosas por qué se hace eso, y de hecho es lo más importante de la asignatura, justificar decisiones técnicas de forma precisa.

2022-01-09 16:19 UTC, JJ commented on docs/CI.md
> +Una vez analizados algunos de los principales sistemas de IC, se ha elegido Circle CI y Github Actions puesto que son los únicos que cumplen todos los requisitos anteriormente mencionados.
Traducido: una vez que he puesto esto porque me pedís que lo ponga, voy a elegir lo que ha elegido todo el mundo y dejarme de tonterías.

2022-01-09 16:19 UTC, JJ commented on docs/CI.md
> +- **Facilidad de uso**: El sistema debe ser fácil de configurar y que no requiera instalación en un servidor.
¿Has puntuado todos los sistemas que has hecho por facilidad de uso? ¿Dónde está esa comparación?

2022-01-09 16:19 UTC, JJ commented on .github/workflows/tests.yml
> +        golang: ['1.16', '1.17']
1.17 ya lo testeas con el contenedor. Estás testeando exactamente lo mismo dos veces. Tenéis que entender por qué se testean diferentes versiones y qué es lo que hay que testear, no simplemente poner unas cuantas versiones (que ni siquiera justificas)

2022-01-09 16:19 UTC, JJ commented on docs/CI.md
> +- **Jenkins**: Proyecto open-source escrito en Java, tiene una interfaz muy intuitiva disponible en Linux, Windows y Mac. Tiene más de 1000 plugins para soportar la integración con muchas herramienta
¿Tiene GitHub checks? ¿Matrix jobs? Si necesita instalación, ¿por qué lo pones aquí siquiera?

2022-01-09 16:19 UTC, JJ commented on docs/CI.md
> +- **TeamCity**: Desarrollado por el equipo de Jetbrains es uno de los sistemas referentes en la industria de la Integración Continua. Tiene una versión gratuita para pequeños proyectos con no más de
¿Tiene GitHub checks? ¿Matrix jobs? ¿Docker hub?

2022-01-09 16:19 UTC, JJ commented on docs/CI.md
> +- **Docker Hub**: Los sistemas deben ser capaces de hacer uso de imágenes de docker que estén subidas a Docker Hub de forma sencilla. Esto facilitará la puesta en marcha del contenedor actualizado ca
Docker Hub no es el único registro.

2022-02-04 20:29 UTC, Xileon310 commented
Cierro el Pull Request para realizar un PR con menos commits y más estructurados.

2022-02-04 20:29 UTC, closed without merging

2022-02-05 10:09 UTC, JJ commented
Recuerda por favor enviarlo de nuevo para que pase los tests.

2022-02-05 10:21 UTC, Xileon310 commented
> Recuerda por favor enviarlo de nuevo para que pase los tests.

No he usado este PR, he creado otro PR (porque estaba demasiado desestructurado en commits). El otro PR sí ha pasado los tests, pero si desea vuelvo a actualizarlo.

2022-02-05 10:27 UTC, JJ commented
No, está bien si has usado otro :-)